# -*- coding: utf-8 -*-
"""BTL Tính toán khoa học

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuzZSaZU-mUZUOi7XNFEM7yY5bpvJ5va
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def laplace_gauss_seidel(nx, ny, max_iter, tol):
    """
    Giai phuong trinh Laplace 2D bang Gauss-Seidel.

    Tham so:
        nx, ny: So diem luoi theo truc x va y
        max_iter: So vong lap toi da
        tol: Sai so cho phep (tolerance)

    Tra ve:
        x, y: Toa do luoi
        p: Nghiem cua phuong trinh
    """
    # Khoi tao luoi va gia tri ban dau
    p = np.zeros((ny, nx))

    # Thiet lap toa do
    x = np.linspace(0, 2, nx)
    y = np.linspace(0, 1, ny)

    # Dieu kien bien
    p[:, 0] = 0       # x = 0, p = 0
    p[:, -1] = y      # x = 2, p = y
    p[0, :] = 0       # y = 0, p = 0
    p[-1, :] = 0      # y = 1, p = 0

    # Vong lap Gauss-Seidel
    for k in range(max_iter):
        p_old = p.copy()

        # Cap nhat gia tri tai cac diem ben trong
        for j in range(1, ny-1):
            for i in range(1, nx-1):
                p[j, i] = 0.25 * (p[j, i+1] + p[j, i-1] +
                                  p[j+1, i] + p[j-1, i])

        # Kiem tra hoi tu
        diff = np.sum(np.abs(p - p_old))
        if diff < tol:
            print(f"Thuat toan hoi tu tai buoc lap thu {k}")
            return x, y, p

    print(f"Chua hoi tu sau {max_iter} buoc lap")
    return x, y, p

def plot_results(x, y, p):
    """Ve bieu do ket qua"""
    X, Y = np.meshgrid(x, y)

    # Contour plot
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    contour = plt.contourf(X, Y, p, 20, cmap='viridis')
    plt.colorbar(contour, label='u(x,y)')
    plt.title('Phan bo nghiem - Contour Plot')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.axis('equal')

    # Line plot tai mot so muc y
    plt.subplot(1, 2, 2)
    for j in [ny_val//4, ny_val//2, 3*ny_val//4]:
        plt.plot(x, p[j, :], label=f'y = {y[j]:.2f}')
    plt.xlabel('x')
    plt.ylabel('u(x,y)')
    plt.title('Phan bo nghiem theo x')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

    # 3D surface plot
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')
    surf = ax.plot_surface(X, Y, p, cmap='viridis',
                           rstride=1, cstride=1,
                           linewidth=0, antialiased=True)
    fig.colorbar(surf, shrink=0.5, aspect=5)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('u(x,y)')
    ax.set_title('Be mat 3D cua nghiem')
    ax.view_init(elev=30, azim=45)
    plt.show()

# Cau hinh tham so
nx_val = 31
ny_val = 31
max_iter_val = 5000
tol_val = 1e-4

# Chay mo phong
print("Bat dau giai phuong trinh Laplace 2D...")
x_res, y_res, p_res = laplace_gauss_seidel(nx_val, ny_val,
                                            max_iter_val, tol_val)

# Hien thi ket qua
print(f"Gia tri lon nhat: {np.max(p_res):.4f}")
print(f"Gia tri nho nhat: {np.min(p_res):.4f}")

# Ve bieu do
plot_results(x_res, y_res, p_res)

